# server
server:
  port: 8080
  servlet:
    context-path: /my-playground

# spring
spring:
  application:
    name: myPlayground
  profiles:
    include: db
  threads:
    virtual:
      enabled: true